"""
STEP 0: REPLACE SYNTHETIC WARDS WITH DIGITISED VMC BOUNDARIES
==============================================================
Slots the digitised VMC official ward boundaries into the pipeline,
replacing the KMeans/Voronoi synthetic wards generated by 02_generate_wards_9km.py.

Run this ONCE before running 03_accessibility_engine.py and all downstream scripts.
The output file path is identical to 02_generate_wards_9km.py so no other script
needs to be changed.

Source:
  Vadodara Municipal Corporation official ward boundary map (19 wards)
  Digitised from image using hybrid watershed + Voronoi segmentation,
  scale-bar calibrated (1 px ≈ 53 m). Positional accuracy ±150 m.
  Total digitised area: 206 km² (VMC official: ~204 km²).

Methodology note for thesis:
  Ward boundaries were digitised from the official VMC ward boundary map
  using a watershed segmentation algorithm seeded by ward number positions.
  The outer VMC boundary was detected via adaptive thresholding and filled
  to constrain peripheral ward extents. The georeferencing transform was
  calibrated using the map's scale bar (8 km reference) anchored to the
  Mandvi Gate intersection (22.2973°N, 73.2062°E), yielding a ground
  resolution of approximately 53 m/pixel.
"""

import geopandas as gpd
import os
import shutil

# --------------------------------------------------
# PATHS
# --------------------------------------------------
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Source: digitised VMC wards (place this file in data/raw/)
VMC_WARDS_SRC = os.path.join(BASE_DIR, "data", "raw", "wards_19_vmcdigitised.gpkg")

# Target: the path all downstream scripts expect
OUTPUT_GPKG = os.path.join(BASE_DIR, "data", "interim", "vadodara_9km_wards.gpkg")

# Backup of synthetic wards (in case you need to revert)
BACKUP_GPKG = os.path.join(BASE_DIR, "data", "interim", "vadodara_9km_wards_SYNTHETIC_BACKUP.gpkg")

PROJECT_CRS = "EPSG:32643"

REQUIRED_COLS = {"ward_id", "ward_name", "area_km2", "geometry"}


def replace_wards():
    print("--- STEP 0: REPLACING SYNTHETIC WARDS WITH VMC BOUNDARIES ---")

    # --------------------------------------------------
    # 1. Validate source file
    # --------------------------------------------------
    if not os.path.exists(VMC_WARDS_SRC):
        raise FileNotFoundError(
            f"❌ VMC wards file not found: {VMC_WARDS_SRC}\n"
            "   Copy wards_19_vmcdigitised.gpkg into data/raw/ first."
        )

    gdf = gpd.read_file(VMC_WARDS_SRC, layer="wards")

    missing = REQUIRED_COLS - set(gdf.columns)
    if missing:
        raise ValueError(f"❌ Missing columns in VMC wards file: {missing}")

    assert len(gdf) == 19, f"❌ Expected 19 wards, found {len(gdf)}"
    assert set(gdf.ward_id) == set(range(1, 20)), "❌ ward_id must be 1–19"
    assert gdf.is_valid.all(), "❌ Invalid geometries found"

    # --------------------------------------------------
    # 2. Reproject to pipeline CRS
    # --------------------------------------------------
    if gdf.crs.to_epsg() != 32643:
        gdf = gdf.to_crs(PROJECT_CRS)
        print(f"   Reprojected to {PROJECT_CRS}")
    else:
        print(f"   CRS already {PROJECT_CRS}")

    # --------------------------------------------------
    # 3. Add pipeline-compatible columns
    # --------------------------------------------------
    gdf["generation_method"] = "VMC official boundary — digitised from ward map image"
    gdf["seed_method"]       = "Watershed segmentation + scale-bar calibration"
    gdf["num_wards"]         = 19
    gdf["crs"]               = PROJECT_CRS

    # --------------------------------------------------
    # 4. Backup synthetic wards if they exist
    # --------------------------------------------------
    if os.path.exists(OUTPUT_GPKG):
        shutil.copy2(OUTPUT_GPKG, BACKUP_GPKG)
        print(f"   Synthetic wards backed up → {BACKUP_GPKG}")

    # --------------------------------------------------
    # 5. Save to pipeline location
    # --------------------------------------------------
    os.makedirs(os.path.dirname(OUTPUT_GPKG), exist_ok=True)
    gdf.to_file(OUTPUT_GPKG, driver="GPKG")

    # --------------------------------------------------
    # 6. Summary
    # --------------------------------------------------
    print(f"\n✅ VMC wards installed at: {OUTPUT_GPKG}")
    print(f"   Wards: {len(gdf)}  |  CRS: {gdf.crs}  |  All valid: {gdf.is_valid.all()}")
    print(f"   Area range: {gdf.area_km2.min():.2f} – {gdf.area_km2.max():.2f} km²")
    print(f"   Total area: {gdf.area_km2.sum():.1f} km²")
    print(f"\n   Next step: run 03_accessibility_engine.py")
    print(f"   To revert: copy {BACKUP_GPKG} back to {OUTPUT_GPKG}")


if __name__ == "__main__":
    replace_wards()
