title: "Urban Inequality in Vadodara"
description: "Geospatial and network-based analysis of urban inequality"
theme: minima

markdown: kramdown
kramdown:
  math_engine: katex

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
